//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nog.Prayas.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event_Gallery
    {
        public int Id { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> EventId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsBaseImage { get; set; }
    
        public virtual Event Event { get; set; }
    }
}
